### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 2lineofcode** [XRadius/javit#1]
javit search MIRD-163
Fetching MIRD-163
Rejected MIRD-163: TypeError: fetch failed
    at node:internal/deps/undici/undici:12442:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.metaAsync (/opt/homebrew/lib/node_modules/javit/dist/functions/metaAsync.js:32:22)
    at async runAsync (/opt/homebrew/lib/node_modules/javit/dist/actions/searchAsync.js:35:19)
    at async traceAsync (/opt/homebrew/lib/node_modules/javit/dist/actions/helpers/traceAsync.js:6:24)
    at async Command.searchAsync (/opt/homebrew/lib/node_modules/javit/dist/actions/searchAsync.js:31:5)

**Comment by 2lineofcode** [comment]
solved with dns 1.1.1.1
